version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookit
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: sh -c "npm run build && npm run start"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build: ./frontend
    command: sh -c "npm run dev -- --host 0.0.0.0"
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
volumes:
  db_data:
